import { describe, it, expect } from 'vitest';
import { formatCurrency, getCurrencySymbol } from '../../src/utils/format';

vi.mock('react-i18next', () => ({
  useTranslation: () => ({
    t: (key: string) => {
      if (key === 'dashboard.locale') return 'pt-BR';
      if (key === 'analytics.search_placeholder') return 'Busque por despesa ou categoria (ex: Uber, Mercado)...';
      if (key === 'dashboard.bill_empty') return 'Nenhuma despesa para esta fatura.';
      if (key === 'dashboard.bill_paid') return 'Fatura Paga';
      return key;
    },
    i18n: { language: 'pt' }
  }),
  initReactI18next: { type: '3rdParty', init: () => {} }
}));

describe('Format Utilities', () => {
  describe('formatCurrency', () => {
    it('should format BRL correctly', () => {
      const result = formatCurrency(1234.56, 'BRL');
      // Fix for internal spaces generated by Intl.NumberFormat in some environments
      const cleanedResult = result.replace(/\u00A0/g, ' ');
      expect(cleanedResult).toContain('R$');
      expect(cleanedResult).toContain('1.234,56');
    });

    it('should format USD correctly', () => {
      const result = formatCurrency(1234.56, 'USD');
      expect(result).toContain('$');
    });

    it('should format EUR correctly', () => {
      const result = formatCurrency(1234.56, 'EUR');
      expect(result).toContain('€');
    });
  });

  describe('getCurrencySymbol', () => {
    it('should return BRL configuration', () => {
      expect(getCurrencySymbol('BRL')).toEqual({ symbol: 'R$', position: 'left' });
    });

    it('should return USD configuration', () => {
      expect(getCurrencySymbol('USD')).toEqual({ symbol: '$', position: 'left' });
    });

    it('should return EUR configuration', () => {
      expect(getCurrencySymbol('EUR')).toEqual({ symbol: '€', position: 'right' });
    });
  });
});
